import { Workflow } from "@skein/schema";

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TYPE_TO_FILE: Record<string, string> = {
  "manual-trigger": "manualTrigger",
  "webhook-trigger": "webhookTrigger",
  "schedule-trigger": "scheduleTrigger",
  "http-request": "httpRequest",
  delay: "delay",
  condition: "condition",
  loop: "stubs",
  transform: "transform",
  "llm-prompt": "llmPrompt",
  "tool-call": "toolCall",
  "log-debug": "logDebug",
};

function getExecutorSource(nodeType: string): string {
  const fileName = TYPE_TO_FILE[nodeType];
  if (!fileName) {
    throw new Error(`Unsupported node type for standalone export: ${nodeType}`);
  }

  const nodesDir = path.resolve(__dirname, "../../nodes");
  const tsPath = path.join(nodesDir, "src/executors", `${fileName}.ts`);
  const jsPath = path.join(nodesDir, "dist/executors", `${fileName}.js`);

  let code = "";

  if (fs.existsSync(tsPath)) {
    const tsCode = fs.readFileSync(tsPath, "utf8");
    try {
      const require = createRequire(import.meta.url);
      const ts = require("typescript");
      code = ts.transpileModule(tsCode, {
        compilerOptions: {
          target: ts.ScriptTarget.ES2022,
          module: ts.ModuleKind.ESNext,
          removeComments: false,
        },
      }).outputText;
    } catch (e) {
      if (fs.existsSync(jsPath)) {
        code = fs.readFileSync(jsPath, "utf8");
      } else {
        throw new Error(
          `Cannot transpile ${tsPath} because typescript package is not available and compiled JS at ${jsPath} does not exist.`,
        );
      }
    }
  } else if (fs.existsSync(jsPath)) {
    code = fs.readFileSync(jsPath, "utf8");
  } else {
    throw new Error(`Executor implementation not found for node type: ${nodeType} (searched in ${tsPath} and ${jsPath})`);
  }

  // Clean imports
  code = code.replace(/import\s+[\s\S]*?\s+from\s+['"].*?['"];?/g, "");

  // Clean exports
  code = code.replace(/\bexport\s+async\s+function\s+/g, "async function ");
  code = code.replace(/\bexport\s+function\s+/g, "function ");
  code = code.replace(/\bexport\s+const\s+/g, "const ");

  // Clean source map URLs
  code = code.replace(/\/\/# sourceMappingURL=.*$/gm, "");

  return code.trim();
}

export function generateStandaloneCode(workflow: Workflow): string {
  // 1. Gather all node types present in the workflow
  const activeTypes = new Set<string>();
  workflow.nodes.forEach((node) => {
    if (node.type) activeTypes.add(node.type);
  });

  // 2. Generate the executor registration map string dynamically
  const executorImportsCode = Array.from(activeTypes)
    .map((type) => getExecutorSource(type))
    .filter(Boolean)
    .join("\n\n");

  const registryMapping = Array.from(activeTypes)
    .map((type) => {
      const camelCaseName =
        type.replace(/-([a-z])/g, (g) => g[1].toUpperCase()) + "Executor";
      return `  '${type}': ${camelCaseName},`;
    })
    .join("\n");

  const requiresVm = activeTypes.has("condition") || activeTypes.has("transform");
  const vmImport = requiresVm ? 'import vm from "node:vm";\n' : '';

  const needsTemplateString = activeTypes.has("http-request") || activeTypes.has("llm-prompt");
  const includesHttpRequest = activeTypes.has("http-request");
  let templateStringHelper = "";
  if (needsTemplateString && !includesHttpRequest) {
    templateStringHelper = `
function templateString(str, variables) {
  return str.replace(/\\{\\{([^}]+)\\}\\}/g, (_, path) => {
    const keys = path.trim().split(".");
    let val = variables;
    for (const key of keys) {
      if (val === null || val === undefined) return "";
      val = val[key];
    }
    return val !== undefined ? String(val) : "";
  });
}
`;
  }

  return `// 🧶 Standalone workflow execution code generated by Skein
// Workflow Name: ${workflow.name}
// Generated At: ${new Date().toISOString()}

${vmImport}
${templateStringHelper}

const workflow = ${JSON.stringify(workflow, null, 2)};

// --- Node Executors ---
${executorImportsCode}

const EXECUTORS = {
${registryMapping}
};

// --- In-Memory Topological Sorted Run Core ---
class StandaloneWorkflowExecutor {
  constructor(workflow) {
    this.workflow = workflow;
    this.results = {};
  }

  async execute(initialPayload = {}) {
    const nodeIds = this.workflow.nodes.map((n) => n.id);
    const inDegree = {};
    const adjList = {};
    const incomingEdges = {};

    nodeIds.forEach((id) => {
      inDegree[id] = 0;
      adjList[id] = [];
      incomingEdges[id] = [];
      this.results[id] = { nodeId: id, status: 'idle' };
    });

    this.workflow.edges.forEach((edge) => {
      if (nodeIds.includes(edge.source) && nodeIds.includes(edge.target)) {
        adjList[edge.source].push(edge.target);
        incomingEdges[edge.target].push(edge);
        inDegree[edge.target]++;
      }
    });

    const activePromises = {};
    const skippedNodes = new Set();
    let runErrorOccurred = null;

    const executeNode = async (nodeId) => {
      const node = this.workflow.nodes.find((n) => n.id === nodeId);
      const edges = incomingEdges[nodeId];
      let inputs = {};
      let isSkipped = skippedNodes.has(nodeId);

      if (!isSkipped && edges.length > 0) {
        let activeIncomingCount = 0;
        edges.forEach((edge) => {
          const parentResult = this.results[edge.source];
          if (parentResult && parentResult.status === 'success' && parentResult.output) {
            const val = parentResult.output[edge.sourceHandle];
            if (val !== undefined) {
              inputs[edge.targetHandle] = val;
              activeIncomingCount++;
            }
          }
        });
        if (activeIncomingCount === 0) {
          isSkipped = true;
        }
      } else if (!isSkipped && node.type === 'manual-trigger') {
        inputs.payload = initialPayload;
      }

      if (isSkipped) {
        this.results[nodeId] = {
          nodeId,
          status: 'skipped',
          startedAt: Date.now(),
          finishedAt: Date.now(),
        };
        adjList[nodeId].forEach((childId) => {
          skippedNodes.add(childId);
        });
      } else {
        this.results[nodeId] = {
          nodeId,
          status: 'running',
          startedAt: Date.now(),
        };

        try {
          const executor = EXECUTORS[node.type];
          if (!executor) {
            throw new Error('No executor found for node type: ' + node.type);
          }

          const output = await executor(node.config || {}, inputs, {
            workflow: this.workflow,
            executors: EXECUTORS,
            nodeId,
          });

          this.results[nodeId] = {
            nodeId,
            status: 'success',
            output,
            startedAt: this.results[nodeId].startedAt,
            finishedAt: Date.now(),
          };
        } catch (err) {
          const errMsg = err.message || String(err);
          this.results[nodeId] = {
            nodeId,
            status: 'error',
            error: errMsg,
            startedAt: this.results[nodeId].startedAt,
            finishedAt: Date.now(),
          };

          const skipDownstream = (id) => {
            adjList[id].forEach((childId) => {
              if (!skippedNodes.has(childId)) {
                skippedNodes.add(childId);
                skipDownstream(childId);
              }
            });
          };
          skipDownstream(nodeId);

          runErrorOccurred = new Error('Node execution failed at node ' + nodeId + ': ' + errMsg);
        }
      }

      const children = adjList[nodeId];
      const nextPromises = [];

      children.forEach((childId) => {
        inDegree[childId]--;
        if (inDegree[childId] === 0) {
          const childPromise = executeNode(childId);
          activePromises[childId] = childPromise;
          nextPromises.push(childPromise);
        }
      });

      await Promise.all(nextPromises);
    };

    const initialNodes = nodeIds.filter((id) => inDegree[id] === 0);
    const initialPromises = initialNodes.map((id) => {
      const p = executeNode(id);
      activePromises[id] = p;
      return p;
    });

    await Promise.all(initialPromises);

    if (runErrorOccurred) {
      throw runErrorOccurred;
    }

    return this.results;
  }
}

export async function run(initialPayload = {}) {
  const runner = new StandaloneWorkflowExecutor(workflow);
  return await runner.execute(initialPayload);
}

// Auto-run when executed directly via Node.js
if (import.meta.url === 'file://' + process.argv[1]) {
  run()
    .then((res) => console.log('Standalone execution result:', res))
    .catch((err) => console.error('Standalone run failed:', err));
}
`;
}
